package com.wnc.createaccount.utils

enum class DkMessageType(val value: Byte) {
    FRAMEWORK_MESSAGE(0x01),
    SUPPLEMENTARY_SERVICE_MESSAGE(0x02),
    DK_EVENT_NOTIFICATION(0x03)
}
enum class DkSubEventCategory(val value: Byte) { COMMAND_COMPLETE(0x01) }
enum class DkSubEventCommandCompleteType(val value: Byte) {
    REQUEST_OWNER_PAIRING(0x01), BLE_PAIRING_READY(0x02)
}

enum class RangingMsgId(val value: Byte) {
    DK_APDU_RQ(0x01), DK_APDU_RS(0x02),
    FIRST_APPROACH_RQ(0x03), FIRST_APPROACH_RS(0x04),
    TIME_SYNC(0x05), DK_EVENT_NOTIFICATION(0x06)
}

enum class AppState { IDLE, EXCHANGE_MTU, SERVICE_DISC, CCC_PHASE2_WAITING_FOR_REQUEST, CCC_PHASE2_WAITING_FOR_VERIFY, CCC_WAITING_FOR_PAIRING_READY, PAIR, RUNNING }
//enum class AppEvent {
//    PEER_CONNECTED, PEER_DISCONNECTED, GATT_PROC_COMPLETE, GATT_PROC_ERROR, SERVICE_DISCOVERY_COMPLETE,
//    SERVICE_DISCOVERY_FAILED, READ_CHARACTERISTIC_VALUE_COMPLETE, PSM_CHANNEL_CREATED, SENT_SPAKE_RESPONSE,
//    RECEIVED_SPAKE_VERIFY, RECEIVED_PAIRING_READY, PAIRING_LOCAL_OOB_DATA, PAIRING_PEER_OOB_DATA_RCV,
//    PAIRING_PEER_OOB_DATA_REQ, PAIRING_COMPLETE, ENCRYPTION_CHANGED, AUTHENTICATION_REJECTED,
//    SHELL_RESET_COMMAND, SHELL_FACTORY_RESET_COMMAND, SHELL_START_DISCOVERY_OP_COMMAND,
//    SHELL_STOP_DISCOVERY_COMMAND, SHELL_SET_BONDING_DATA_COMMAND, SHELL_LIST_BONDED_DEV_COMMAND,
//    SHELL_REMOVE_BONDED_DEV_COMMAND, SHELL_DISCONNECT_COMMAND,
//    KBD_EVENT_PRESS_PB1, KBD_EVENT_LONG_PB1, KBD_EVENT_VERY_LONG_PB1
//}